### ISSUE TITLE
Excel Macro-Enabled Workbook (.xlsm) should be used instead of .xlsx

### ISSUE THREAD

**Issue by mincong-h** [hiddenllyy/Internship-with-VBA#1]
Hi @hiddenllyy ,

You should upload Excel Macro-Enabled Workbook `.xlsm` instead of `.xlsx`, because there's no VBA modules in `.xlsx` file.

**Comment by hiddenllyy** [comment]
Moring @mincong-h ,
I've arrived at company and I've created a new file no-confidential for you so that both of us can do the test together with the same file and content.
And I've tried to use ENTER as a seperater but failed, do you have some resolutions or other recommands?

**Comment by mincong-h** [comment]
As you've fixed the `.xlsm` in commit 89c7812, I'll close this issue now. One issue aims to focus and treat only one problem. The separator problem will be treated in the 2nd issue.
