### ISSUE TITLE
Use second normal form for data storage

### ISSUE THREAD

**Issue by mincong-h** [hiddenllyy/Internship-with-VBA#11]
In the current implementation in excel worksheet, the data has been probably stored. However, it could have been even better for further usages, e.g. filter and data analyse. The 2NF, [second normal form](https://en.wikipedia.org/wiki/Second_normal_form), should be an easy and suitable implementation. Here's an example comparison:

The current form looks like :

| F | G | H |
| --- | --- | --- |
| Res1.txt | conforme : non |  |
|  | Zone 1 : invalide |  |
|  | Zone 2 : non conforme | presence percage : OK |
| Res2.txt | conforme : non |  |
|  | Zone 1 : invalide |  |

The new form looks like :

| F | G | H | I | J |
| --- | --- | --- | --- | --- |
| File | FIleConformite | Zone | ZoneConformite | percage |
| Res1.txt | non | 1 | invalide |  |
| Res1.txt | non | 2 | non | OK |
| Res2.txt | non | 1 | invalide |  |

**Comment by hiddenllyy** [comment]
The problem is, for each type of test, the criterions are not the same, so I think for each type, I have to write a `Case` function and handle them seperately.

**Comment by mincong-h** [comment]
> The problem is, for each test, the criterions are not the same,

What do you mean by "test" ? Do you mean the data extraction from txt files and data transformation ?

> so I think for each type, I have to write a `Case` function and handle them seperately.

You can either do this or create a look up function to find where the correspondent column in worksheet.

**Comment by hiddenllyy** [comment]
> What do you mean by "test" ?

For exemple, a test for the button, there are 4 criterions, such as : the form is good or not? The couleur is good or not, etc.
And the test for a piece of metal, there are 6 criterions instead.

> You can either do this or create a look up function to find where the correspondent column in worksheet.

And so, according to the variable situation for each test, i'd rather write a `Case` function. Look up function, I think the work is also complicated. Cause the key word I have to find is as much as `Case` function has to achieve.

**Comment by mincong-h** [comment]
Ah, OK. But if the number of criterions are not the same, then the comparison still makes sense ? If yes, then create a workdsheet containing M + N columns , where M is the 4 criterions and N is the 6 criterions. Else, rather use 2 worksheet.

**Comment by hiddenllyy** [comment]
That would be more complicated because we have totally 6 test (for button, for metal, for wire, for screws etc), that means I have to handle a 6-dimension work. 
I want to achive the very simple function, if there is one criterion unsatisfaied then this button is not valid. so no matter 6 or 4 or just 1 criterion it has, it becomes simple. 
And I think for the company, the idea is also the same, once there is a problem, this button can not be put into service.

**Comment by hiddenllyy** [comment]
Good mroning Mincong,
It's been a long time that I haven't worked. Yesterday we had a really large strike and monday I had a one day leave.
So this week, which has only three days left, I'll still work on VBA but not totally the same userform that I've showed you. Instead, we have a brand new report in EXCEL and i'll try to make it complete the table by itself. So I'll work more with ActiveX controls.
That's it. We'll keep in contact and I wish you have a good week.
See you soon.

**Comment by mincong-h** [comment]
Happy to hear from you. Let's keep in touch :smile:
