### ISSUE TITLE
VBA_OptionButton selected by default at the begining

### ISSUE THREAD

**Issue by hiddenllyy** [hiddenllyy/Internship-with-VBA#12]
Good morning,

I'd like to creat a userform with two optionButtons and a several frames. The optionButton1 can disable a frame and some buttons. The optionButton2 can enable these frames and buttons. I've used this code to make optionButton1 enable by default. But the function can not be done with it:

``` vba
OptionButton1.value = 1
```

The button is selected but the frame and the buttons are still enable. So do you have some advices for this?

**Comment by mincong-h** [comment]
I've never used this. Maybe take a look at [MSDN | Grouping Options with Option Buttons](https://msdn.microsoft.com/en-us/library/aa241737%28v=vs.60%29.aspx) ?

**Comment by hiddenllyy** [comment]
Or do you know how to make a sub run automatically when I run the Macro?

**Comment by mincong-h** [comment]
you can assign a sub to a button directly. this button locates inside the worksheet
