### ISSUE TITLE
VBA_Error '1004' while using the InStr Function

### ISSUE THREAD

**Issue by hiddenllyy** [hiddenllyy/Internship-with-VBA#13]
Good morning,

I'd like to use a For cycle to compare two sheets' content, and do something if the condition is satisfied.
Here is the code: 

``` vba
For j = 1 To ligne_Brouillon

    If InStr(Sheets("Brouillon").Cells(j, 7).Text, Sheets("Data").Cells(i, 18).Text) <> 0 Then  'compare two cells' content

        For k = 8 To colonne_brouillon

            If InStr(Sheets("Brouillon").Cells(j, k).Text, Sheets _("Data").Cells(i, 20).Text) <> 0 Then  'if the first cell contents the keyword
                Sheets("Data").Cells(i, ma_Colonne).Text = Sheets _("Brouillon").Cells(j, k).Text
            End If

        Next

    End If

Next
```

 i've tried some methods to fix this but failed. So if you got some ideas please give me some advices. Thanks in adcance!

**Comment by mincong-h** [comment]
Could you provide more detail about the failure message ? It is very important for debugging. Else, try to do 2 things : 
1.  Always point the iteration variable after `Next`, that will be more explicit. For example : 
   
   ``` vba
   For i = 1 To 10
      For j = 1 To 10
          Debug.Print i & "," & j
      Next j
   Next i
   ```
2.  Use more variables and make your line containing as less info as possible. For example : 
   
   ``` vba
   Dim searchStr As String
   Dim keyword As String
   Dim keywordPos As Integer
   
   Set keyword = Sheets("Data").Cells(i, 18).Text
   Set searchStr = Sheets("Brouillon").Cells(j, 7).Text
   keywordPos = InStr(searchStr, keyword)
   
   If (keywordPos <> 0) Then
     ' ...
   End If  
   ```

**Comment by hiddenllyy** [comment]
It's became complicated... I'll give you a new version of code after my arrangement of all the Sub and Functions. Thank you.

**Comment by mincong-h** [comment]
Okay, leave a comment or tag me when you finish.

**Comment by hiddenllyy** [comment]
@mincong-h I've rewrite the code and here is the new problem #14
