### ISSUE TITLE
Problem of importing the data to EXCEL

### ISSUE THREAD

**Issue by hiddenllyy** [hiddenllyy/Internship-with-VBA#14]
Good Morning,

I've met a problem when I tried to import the data into EXCEL. When I want to open a file (according to the list of control) and import the data into a new sheet named "Brouillon", it can not do it. The new sheet "Brouillon" is empty. But I've done it before, it works well. I've tried to change every line that I've added after into commend but it doesn't help. So did you have met this before or your know the reason?

``` vba
Public listPath As String
Public ligne_Data As Integer
Public ma_Colonne As Integer

Public mon_Objet As String
Public nom_de_Fich As String
Public ligne_Brouillon As Integer
Public colonne_Brouillon As Integer


Private Sub Button_Importer_Click()

    list_de_controle = "TEXT;" & listPath

    Worksheets(Array(1)).Select
    Range("A3").Select
    ActiveCell.End(xlToRight).Select
    ActiveCell.End(xlDown).Select
    ligne_Data = Selection.Row
    ma_Colonne = Selection.Column + 1

    Debug.Print ligne_Data
    Debug.Print ma_Colonne


    Open listPath For Input As #1

    For i = 3 To ligne_Data  'pour chaque ligne dans la feuil "Data"
        mon_Objet = Cells(i, 15).Text + "_" + Cells(i, 17).Text

        Do While Not EOF(1)  'Chercher le fichier dans la list
            Line Input #1, nom_de_Fich
            mfile = Dir(nom_de_Fich & "*.*")

            If InStr(nom_de_Fich, mon_Objet) > 0 And mfile <> "" Then  'Si on le trouve et il existe
                GoTo_Brouillon
                Open nom_de_Fich For Input As #2
                Insérer_contenu
                Close #2

            End If

        Loop

    Next i

    Close #1

End Sub

Public Sub Insérer_contenu()

    Dim keyWord As String

    keyWord = "Zone"
    Insérer_Nom_Fich

    Do While Not EOF(2)
        Line Input #2, contenu

        If InStr(contenu, keyWord) < 1 Then  'ce n'est pas une nouvelle zone
            ActiveCell = contenu
        Else                                 'si c'est une nouvelle zone
            ActiveCell.Offset(1, 0).Select
            ActiveCell.End(xlToLeft).Select
            Insérer_Nom_Fich
            ActiveCell = contenu
        End If

        ActiveCell.Offset(0, 1).Select

    Loop

    ActiveCell.Offset(1, 0).Select
    ActiveCell.End(xlToLeft).Select

End Sub


Public Sub Insérer_Nom_Fich()

    Dim WrdArray() As String
    Dim wrd As Variant

    WrdArray() = Split(nom_de_Fich, "_")

    For Each wrd In WrdArray
        ActiveCell.Value = wrd
        ActiveCell.Offset(0, 1).Select
    Next

End Sub

```

**Comment by mincong-h** [comment]
So the error is thrown in the below line ? 

```
If InStr(Sheets("Brouillon").Cells(j, 7).Text, Sheets("Data").Cells(i, 18).Text) <> 0 Then  'zone
```

**Comment by mincong-h** [comment]
This is weird because `Sheets("Brouillon")` should be fine. Maybe the `.Text` is empty ?

**Comment by hiddenllyy** [comment]
Oh perhaps, I'll try `.Value` instead.

**Comment by hiddenllyy** [comment]
Ah no, this line
`If InStr(Sheets("Brouillon").Cells(j, 7).Text, Sheets("Data").Cells(i, 18).Text) <> 0 Then`
is a comment. The part before `Close #2` doesn't work. The Brouillon is still empty. :cry:

**Comment by mincong-h** [comment]
Avoid using `ActiveCell` in your sub `Insérer_Nom_Fich()`. Can your give the cells position explicitly ? e.g

```
Set Sheets("MySheet").Cells(x, y).Value = wrd
```

**Comment by mincong-h** [comment]
I don't know where the error comes from. Try the execution step by step using <kbd>F8</kbd>

**Comment by hiddenllyy** [comment]
Oh I've found that. It's `If InStr(nom_de_Fich, mon_Objet) > 0 And mfile <> "" Then`
Here is the problem. It just jump to next without doing anyting.

**Comment by mincong-h** [comment]
Cool :+1:

**Comment by hiddenllyy** [comment]
But I don't know how to fix it

**Comment by hiddenllyy** [comment]
I don't see there is any problem

**Comment by mincong-h** [comment]
:broken_heart:

**Comment by hiddenllyy** [comment]
I've a meeting to attend, I'll contact you this afternoon and tell you the process.

**Comment by mincong-h** [comment]
ok

**Comment by hiddenllyy** [comment]
Hi Mincong, I've figured it out. The problem is with the `Do While Not EOF(1)` line. Because the first cycle in `For i = 3 To ligne_Data`, the `#1` file has already reached the end. So in all the following cycle in `For`, this line can not be satisfied. So it can only work for the first time. And I've put it into the `For` cycle and it works. Just a little bit slowly... :cry:

**Comment by mincong-h** [comment]
What about alternate these 2 loops : 
-  Now, the `For` loop embeds the `Do While` loop
-  Can the `Do While` loop embeds the `For` loop ? 

So that you open the file and read the data for once. Then, you look up fields to be filled in your worksheet

**Comment by hiddenllyy** [comment]
Oh I see, you want to reduce the times that I open the list, is it? I've tried but this line `Line Input #1, nom_de_Fich` has depassed the end of the file. Perhaps the `EOF` has nolonger control of the inner cycle.

**Comment by hiddenllyy** [comment]
Oh I see, you want to reduce the times that I open the list, is it? But this line `Line Input #1, nom_de_Fich
` is depassed the end of the file. Perhaps the `EOF` can no longer control the cycle.

**Comment by mincong-h** [comment]
I think the problem's complexity is beyond my writing skills :sweat_drops: :sweat_drops: :sweat_drops: If your new code works, then we can consider the problem resolved (even though it might not be the optimizest one).

**Comment by hiddenllyy** [comment]
Haha that's my recently goal. Just want a code which can work... no matter how slow it does.
