### ISSUE TITLE
VBA_How to use a dynamic array?

### ISSUE THREAD

**Issue by hiddenllyy** [hiddenllyy/Internship-with-VBA#15]
Good morning,
I'd like to use a dynamic array to reserve a new list. I've no idea how many elements I'll have to add in the array. and the code is already long so I don't know how to put a `For` Cycle in it. So I'd like to know if I can use a line like `array1() = "something i want to put into array"` and I don't need to worry about the indice in the array1?

**Comment by mincong-h** [comment]
I met a similar pb yesterday, check my code here https://github.com/mincong-h/vba/blob/2d4718abf64bf65906c58473707bf6bac98a1c72/Orange/DVI/datacrawler/CrawlerModule.vba#L57-L74 It might give you some ideas

**Comment by mincong-h** [comment]
http://analystcave.com/excel-vba-dictionary-arrays-and-other-data-structures/#The_VBA_ArrayList_object

``` vba
Dim arrList as Object
Set arrList = CreateObject("System.Collections.ArrayList") 'Create the ArrayList
arrList.Add "Hello"
arrList.Add "You"
arrList.Add "There"
arrList.Add "Man"
arrList.Remove "Man"

'Get number of items
Debug.Print arrList.Count 'Result: 3 

For Each item In arrList
  Debug.Print item
Next Item
```

**Comment by hiddenllyy** [comment]
> Dim arrList as Object

This could help.

**Comment by hiddenllyy** [comment]
Thay works! I've made a great process and it's almost done. I hope before this weekend, I can deliver a prototype to my tutor.

**Comment by mincong-h** [comment]
Congratulations !!! :smile_cat:
