### ISSUE TITLE
VBA_Fatal problem of algorithm

### ISSUE THREAD

**Issue by hiddenllyy** [hiddenllyy/Internship-with-VBA#17]
The algorithm is too 'heavy' to run. It'll block after one or two seconds.
A code can not run is useless...
So the basic structure should be all rebuilt.

**Comment by mincong-h** [comment]
Hi @hiddenllyy , I've created a milestone for you. You can use milestone to set up your work progress and describe functionalities inside a milestone. Multiple issues can be assigned to the same milestone. If you assign 3 issues to a milestone, and 2 of them are resolved. Then you can see the milestone progress as 67%. You can also set up a deadline for a milestone, e.g. the next Friday 24 June 2016.

**Comment by hiddenllyy** [comment]
Thanks! It seems like a momument! And if you're free tonight, may I talk about this with you? I need a brand new idea of the algorithm and the structure. My brain has been washed by the current one, so I think a discussion with somebody else would be helpful.

**Comment by hiddenllyy** [comment]
Hi @mincong-h ,
I've had a discussion with my tutor, and he suggested me to use a new method to search the list (it's binomiale or something? I don't know the name). Well , it's like to cut the list into 2 parts, for a new inut, I'll find in which part it belongs, and the go to that one. Then in this part, I repeat the same method, cut it into 2 parts and find its new demi-part. It's a function that contains in EXCEL, perhaps, he's not sure, but he suggested me to search on the Internet.
And I've also explained the new method that we've discussed yesterday, and forbit the UI to refresh. He thought it could be helpful too, and so he suggested me to use a timer to note the time each metod would take.
So can I creat 3 branch in one repository? I'll note separately these three process.

**Comment by hiddenllyy** [comment]
Oh and besides, how can I change it to a private respository? I don't want to be arrested because of brodcasting the confidential things... even the code I'd keep it secret.

**Comment by mincong-h** [comment]
Hi @hiddenllyy, I'm also a beginner in these fields. However, let's discuss together :smile: 

>  he suggested me to use a new method to search the list (it's binomiale or something? I don't know the name). [...]

I think it's a B-tree structure. You can find the definition in wikipedia [B-tree](https://en.wikipedia.org/wiki/B-tree). In computer science, a B-tree is a self-balancing tree data structure that keeps data sorted and allows searches, sequential access, insertions, and deletions in logarithmic time `O(log n)`. 

> And I've also explained the new method that we've discussed yesterday, and forbit the UI to refresh.

``` vba
Application.ScreenUpdating = False
' implement your algorithm
' ...
Application.ScreenUpdating = True
```

> So can I creat 3 branch in one repository? I'll note separately these three process.

You might need to install a [Github Desktop for Windows](https://desktop.github.com/) but **it should be forbidden in your company's intranet**. And I don't recommand you to do so. Your excel files are binary files, it's difficult(impossible) to handle conflicts with binary.

> Oh and besides, how can I change it to a private respository? I don't want to be arrested brcause of brodcasting the confidential files...

You need to pay for it. It's $7 / month.

**Comment by mincong-h** [comment]
Don't tell your boss that you're using GitHub. He might be really unhappy with it

**Comment by hiddenllyy** [comment]
> I think it's a B-tree structure

Yes i think it is. I'll take a glace of it and tell you more details about it.

> You need to pay for it. It's $7 / month.

It's not for free, so I'll not use it. :laughing: 

And I see, since I've received the new EXCEL with all the data inside, I've stopped to upload anything to GitHub... perhaps the code doesn't matter, it contains nothing important. But just in case, I'll pay more attention about that.

**Comment by mincong-h** [comment]
> It's not for free, so I'll not use it. :laughing:

Ok, then :)

> And I see, [...]

You can upload only the .vba file as I do. Then they won't be binary files anymore.

**Comment by hiddenllyy** [comment]
> You can upload only the .vba file 

How to reverve as .vba file?

**Comment by hiddenllyy** [comment]
I think it was because the code is not 'light' enough, so I've been working on it to release the burden and reduce some useless extra progress. And now it works, stil a little bit slow, it takes less than 10 minutes to fill the total 15000 lines. So there's still espace to perfect the code I think. But it's no more fatal.
