### ISSUE TITLE
Try to use ENTER as a seperator but failed

### ISSUE THREAD

**Issue by mincong-h** [hiddenllyy/Internship-with-VBA#2]
Repost of @hiddenllyy in issue #1 : 

> Moring @mincong-h ,
> I've arrived at company and I've created a new file no-confidential for you so that both of us can do the test together with the same file and content.
> And I've tried to use ENTER as a seperater but failed, do you have some resolutions or other recommands?

**Comment by mincong-h** [comment]
Could you tell me where you've tried to split the string using ENTER separator ? It is located in the below lines, e.g. `.TextFileOtherDelimiter` ?

``` vba
' <4> Afficher la liste de controle dans la Feuil active
With ActiveSheet.QueryTables.Add( _
    Connection:=list_de_controle, _
    Destination:=Range("$B$2"))
    .Name = "list_1"
    .TextFileColumnDataTypes = Array(1)
    .TextFileOtherDelimiter = "_"  'utiliser _ comme séparateur
    .TextFileColumnDataTypes = Array(1, 1, 1, 1, 1, 9)  'supprimer la dernière colonne (res.txt) et afficher
    .TextFileTrailingMinusNumbers = 
    .Refresh BackgroundQuery:=False
End With
```

**Comment by hiddenllyy** [comment]
I tried to use ENTER but EXCEL doesn't recognise it, so I use "_" as seperator.
And this part of code just put the list of test (all the name of fiches txt i want to open) in the EXCEL, and about how to withdraw the details in the fiches, I'm still working on it.

**Comment by mincong-h** [comment]
try vbLf

http://stackoverflow.com/questions/8669788/how-to-use-split-to-tokenize-text-file-using-the-new-line-character-as-a-delimit
