### ISSUE TITLE
Version control

### ISSUE THREAD

**Issue by mincong-h** [hiddenllyy/Internship-with-VBA#4]
The version control in git is handled by commits. It means that, if you want to update a file and assign a new version, just overwrite the existing one. You should never create a new file, only for the version-saving propose. This is absolutely the contrary to the git concept.

![18333fig0102-tn](https://cloud.githubusercontent.com/assets/10179217/15431598/e92d9598-1eaa-11e6-8ee2-4d61b9197cfb.png)

For example, if you overwirte the existing UML file, you can always found the previous versions in [commits](https://github.com/hiddenllyy/Internship-with-VBA/commits/master).

**Comment by hiddenllyy** [comment]
Thank you, I've just seen your commant. And this weekend I didn't break through the problem of the path yet. I'll still work on that.

**Comment by mincong-h** [comment]
Fixed at commit 9d4b8d9.
