### ISSUE TITLE
What does 'Binary' mean in this case?

### ISSUE THREAD

**Issue by hiddenllyy** [hiddenllyy/Internship-with-VBA#5]
I've seen this line of code
`Open "TESTFILE" For Binary As #1`
but I don't understand well what exactly does Binary mean?

**Comment by mincong-h** [comment]
Did you see it in [MSDN | Open Statement](https://msdn.microsoft.com/en-us/library/office/gg264163.aspx) ?

``` vba
Open "TESTFILE" For Binary Access Write As #1 
```

Microsoft Office files are all binary files it means that they're written in binary mode (maybe?), like `0011110101...`. Other keywords are explained in the [above link](https://msdn.microsoft.com/en-us/library/office/gg264163.aspx).

**Comment by hiddenllyy** [comment]
Yes, my comprehension is the mode is just what we want to do with this file. As Output for example, means we want to us this file as a return? Is that correct?

**Comment by mincong-h** [comment]
I'm sorry, I don't understand the explanation in that MSDN document and I've never used this OPEN statement before.

**Comment by hiddenllyy** [comment]
Okay it doesn't matter! I've figer it out, 
`Line Input #1, fichOpen`
`Open fichOpen For Input As #1`
like this and it works.
