### ISSUE TITLE
Where does Debug.Print show me the anwers?

### ISSUE THREAD

**Issue by hiddenllyy** [hiddenllyy/Internship-with-VBA#7]
Like title, I'm learning VBA by trying some examples in the book but this function Debug.Print never shows me the answer like msgBox.

**Comment by hiddenllyy** [comment]
For example:
`Sub DisplayDiscount()
Dim unitsSold As String

myMonth = InputBox("Enter a month:")

Select Case myMonth
Case "January", "February", "March"
Debug.Print myMonth & ": 1st Qtr."
Case "April", "May", "June"
Debug.Print myMonth & ": 2nd Qtr."
Case "July", "August", "September"
Debug.Print myMonth & ": 3rd Qtr."
Case "October", "November", "December"
Debug.Print myMonth & ": 4th Qtr."
End Select

End Sub`

**Comment by mincong-h** [comment]
In French, it is called **Fenêtre Exécution**.

![issue-7](https://cloud.githubusercontent.com/assets/10179217/15579373/b07f476e-2364-11e6-8b23-da87e9c47d76.png)

Or your can use your keybroad shortcut <kbd>Ctrl</kbd> + <kbd>G</kbd>.

**Comment by mincong-h** [comment]
@hiddenllyy , can i give you a little exercise ? Highlight your code in your question using the [markdown syntax](https://guides.github.com/features/mastering-markdown/#examples). Once you click the link, you can switch to `code` example to see how people use it.

**Comment by hiddenllyy** [comment]
Ah thank you! That would be really helpful, I can find some solutions by myself.
