### ISSUE TITLE
'Objet requis' error

### ISSUE THREAD

**Issue by hiddenllyy** [hiddenllyy/Internship-with-VBA#8]
Good morning Mincong,

Here I do a little test to check the bug in each line. And I think I 've met an old 'friend'. Like this code:

``` vba
Sub readAll()
    Dim all As String

    Open "\\fichier-lh\users\Desktop\VBA_TEXT\list_à_test.txt" For Input As #1
    all = Input(LOF(1), #1)
    debut.Print
    Close #1
End Sub
```

And there is always the error 'objet requis'. I've no idea how to fix this. Perhaps you can figure the problem out?

**Comment by hiddenllyy** [comment]
it's seems like 'One Day, One Issue' mode. :laughing:

**Comment by mincong-h** [comment]
> it's seems like 'One Day, One Issue' mode. :laughing: 

Good luck !

Maybe there's not such a file in your target path ? Your code works for me. (`debut.Print` should `Debug.Print`)

**Comment by mincong-h** [comment]
BTW, I've changed your markdown syntax. Please check

**Comment by mincong-h** [comment]
Don't put your real id here. It is dangerous.

**Comment by hiddenllyy** [comment]
> Don't put your real id here. It is dangerous.

My id?! Where did I show it?

**Comment by mincong-h** [comment]
n0586641

**Comment by hiddenllyy** [comment]
Oh! I've just saw that. Thank you!! I'll pay attention.

**Comment by hiddenllyy** [comment]
Oh and what's  markdown syntax? In with code have you changed? :cry:

**Comment by mincong-h** [comment]
I'll explain you by telephone tonight or another night
