### ISSUE TITLE
Error 'Entrée dépasse la fin de ficher'

### ISSUE THREAD

**Issue by hiddenllyy** [hiddenllyy/Internship-with-VBA#9]
Good Morning Mincong,

I've met a problem, as title. Here is the code:

``` vba
Private Sub Boutton_Importer_Click()

    list_de_controle = "TEXT;" & listPath
    Open listPath For Input As #1

    Do While Not EOF(1)
        Line Input #1, nom_de_Fich
        ActiveCell = nom_de_Fich
        ActiveCell.Offset(0, 1).Select

        Open nom_de_Fich For Input As #2

        Do While Not EOF(1)
            Line Input #2, contenu
            ActiveCell = contenu
            ActiveCell.Offset(0, 1).Select
        Loop
        Close #2

        With ActiveCell
        .Offset(1, 0).Insert
        End With

    Loop
    Close #1

End Sub

```

You saw, that I've 2 cycles, and the first one, for the nom_de_fich, runs well during the test.
But the second one, it's always blocked, but their codes are exactly the same. So i don't know how to slove the problem. I've check the concents in each file but nothing has been found.
Thank in advance! Have a good raining day :smile:

**Comment by mincong-h** [comment]
Good raining day :joy::joy::joy:
I don't have much time today. I'll check it tonight, maybe after 22h30

**Comment by hiddenllyy** [comment]
http://stackoverflow.com/questions/37540762/vba-using-line-input-but-failed-error-62-input-past-end-of-file
The problem has been solved, thank you and don't squeeze your time on it. Perhaps I'll give you another one this afternoon!!! StackOverFlow is really fast!!!! And full of magic people I have to say :laughing:

**Comment by mincong-h** [comment]
Congratulations @hiddenllyy. Your URL syntax is not correct, you can see mine here : 
- URL with `<YOUR URL HERE>` : 
  
  http://stackoverflow.com/questions/37540762/vba-using-line-input-but-failed-error-62-input-past-end-of-file
- URL using concatenated markdown syntax : 
  
  [VBA_using 'Line Input' but failed (Error 62: Input past end of file)](http://stackoverflow.com/questions/37540762/vba-using-line-input-but-failed-error-62-input-past-end-of-file)
- URL using seperated markdown syntaxt : 
  
  [VBA_using 'Line Input' but failed (Error 62: Input past end of file)](http://stackoverflow.com/questions/37540762/vba-using-line-input-but-failed-error-62-input-past-end-of-file)

**Comment by mincong-h** [comment]
There're many excellent developers there, extremely high level !! Enjoy :smiley:

**Comment by mincong-h** [comment]
I've upvoted your question and the answer. Happy coding !!

**Comment by hiddenllyy** [comment]
Ah I see, I've change the URL and it works now! Thx!
